spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: imovel
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis
logging:
  level:
    org:
      springframework:
        data:
          mongodb: DEBUG
